const wrestlers=[
['Hulk Hogan', '01.jpg'],['Macho Man Randy Savage', '02.jpg'],['Ric Flair', '03.jpg'],['Roddy Piper', '04.jpg'],['Andre the Giant', '05.jpg'],['Ultimate Warrior', '06.jpg'],['Big Boss Man', '07.jpg'],['Akeem', '08.jpg'],['Bret Hart', '09.jpg'],['Sting', '10.jpg'],['Magnum T.A.', '11.jpg'],['Greg “The Hammer” Valentine', '12.jpg'],['The Iron Sheik', '13.jpg'],['Tito Santana', '14.jpg'],['Yokozuna', '15.jpg'],['Blackjack Mulligan', '16.jpg'],['King Harley Race', '17.jpg'],['Ravishing Rick Rude', '18.jpg'],['Shawn Michaels', '19.jpg'],['Jake “The Snake” Roberts', '20.jpg'],['Bam Bam Bigelow', '21.jpg'],['Brutus “The Barber” Beefcake', '22.jpg'],['King Kong Bundy', '23.jpg'],['Ted DiBiase', '24.jpg']
];
let mystery=null, selecting=false, knocked=new Set(), gameOver=false;
const board=document.getElementById('board'),hint=document.getElementById('hint'),status=document.getElementById('status');
function render(){board.innerHTML='';wrestlers.forEach((w,i)=>{const t=document.createElement('button');t.className='tile'+(knocked.has(i)?' knocked':'')+(selecting&&mystery===i?' mystery-choice':'');t.dataset.i=i;t.setAttribute('aria-label',w[0]);t.innerHTML=`<img src="assets/${w[1]}" alt="${w[0]}"><span class="tile-name">${w[0]}</span>`;t.onclick=()=>tap(i);board.appendChild(t)})}
function tap(i){if(gameOver)return;if(selecting){mystery=i;selecting=false;status.textContent='MYSTERY SET';hint.innerHTML='<b>Mystery wrestler selected.</b> Tap tiles to knock them down — tap the mystery wrestler to win.';render();return}if(mystery===null){hint.innerHTML='<b>Choose the mystery wrestler first.</b> Tap SET MYSTERY, then tap one tile.';return}if(i===mystery){gameOver=true;document.querySelector(`[data-i="${i}"]`)?.classList.add('correct-flash');document.getElementById('winnerName').textContent=wrestlers[i][0];setTimeout(()=>document.getElementById('winner').classList.remove('hidden'),250);return}knocked.add(i);render()}
document.getElementById('newGame').onclick=()=>{mystery=null;selecting=false;knocked.clear();gameOver=false;status.textContent='HOST MODE';hint.innerHTML='Tap <b>SET MYSTERY</b>, then tap one wrestler. After that, tap tiles to knock them down.';document.getElementById('winner').classList.add('hidden');document.getElementById('answerModal').classList.add('hidden');render()};
document.getElementById('setMystery').onclick=()=>{mystery=null;selecting=true;status.textContent='SELECT MYSTERY';hint.innerHTML='<b>Now tap the mystery wrestler.</b> This choice is hidden after selection.';render()};
document.getElementById('standAll').onclick=()=>{knocked.clear();render()};
document.getElementById('showAnswer').onclick=()=>{if(mystery===null){hint.innerHTML='<b>No mystery wrestler is selected yet.</b>';return}document.getElementById('answerImage').src=`assets/${wrestlers[mystery][1]}`;document.getElementById('answerName').textContent=wrestlers[mystery][0];document.getElementById('answerModal').classList.remove('hidden')};
document.getElementById('closeAnswer').onclick=()=>document.getElementById('answerModal').classList.add('hidden');document.getElementById('winnerClose').onclick=()=>document.getElementById('winner').classList.add('hidden');document.getElementById('winner').onclick=e=>{if(e.target.id==='winner')e.currentTarget.classList.add('hidden')};
render();
